| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |

# NUMPY - Data Manipulation

In [1]:
import numpy as np

## 1. Slicing Array


### A. Slicing 1-D Array

In [6]:
# Slicing merupakan salah satu cara untuk mengambil lebih dari 1 value pada data array

D = np.array([1,2,3,4,5])

print(D[1:5])
print(D[2:4])
print(D[3:])
print(D[:3])

# [data ke- : data ke-]

[2 3 4 5]
[3 4]
[4 5]
[1 2 3]


### B. Slicing 2-D Array

In [14]:
E = np.array([[1,2,3],[4,5,6]])

print(E[1, 0:3])
print(E[0, 1:3])

# [array ke-, data ke- : data ke-]

[4 5 6]
[2 3]


In [20]:
# Mengambil index elemen yang sama pada kedua array

print(E[0:2, 2])
print(E[0:2, 1])
print(E[0:2, 0])

[3 6]
[2 5]
[1 4]


### C. Slicing 3-D Array

In [28]:
F = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(F)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
print(F[1,0,2])
print(F[0,1,0])

# [array ke- , row, column]

9
4


## 2. Mengubah Nilai Data

Setiap elemen yang terdapat pada array dapat dimanipulasi dengan mengubah data tersebut

### A. Mengubah Nilai pada 1-D Array

In [35]:
# Hal pertama yang dilakukan adalah dengan mengakses data yang akan diubah
# Setelah data didapatkan, maka data tersebut dapat diubah nilainya

D = np.array([1,2,3,4,5])

print(D)

[1 2 3 4 5]


In [37]:
D[2] = 12
D[4] = 20

print(D)

[ 1  2 12  4 20]


### B. Mengubah Nilai pada 2-D Array

In [32]:
E = np.array([[1,2,3],[4,5,6]])

print(E)

[[1 2 3]
 [4 5 6]]


In [33]:
E[0,2] = 10
E[1,1] = 20

print(E)

[[ 1  2 10]
 [ 4 20  6]]


In [27]:
E = np.array([[1,2,3],[4,5,6]])

E[0,2] = 10
E[1,1] = 20
E[: , 0] = [50,50]

print(E)

[[50  2 10]
 [50 20  6]]


### C. Mengubah Nilai pada 3-D Array

In [31]:
F = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(F)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
F[0,0,2] = 150
F[1,0,0] = 70

print(F)

[[[  1   2 150]
  [  4   5   6]]

 [[ 70   8   9]
  [ 10  11  12]]]


In [40]:
F[0,0,2] = 150
F[1,0,0] = 70
F[:,1,1:] = [50,50]

print(F)

[[[  1   2 150]
  [  4  50  50]]

 [[ 70   8   9]
  [ 10  50  50]]]
