| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |


# NUMPY - Mathematics | Statistics

In [1]:
import numpy as np

## 1. Minimum

In [33]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
# Untuk mengetahui data yang paling kecil/minimum pada array dapat menggunakan "np.min"

print(A)

np.min(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


1

In [39]:
print(B)

np.min(B[1])

[[1 2 3]
 [4 5 6]]


4

In [48]:
print(C)

np.min(C[1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


10

## 2. Maksimum

In [35]:
# Untuk mengetahui data yang paling besar/maksimum pada array dapat menggunakan "np.max"

A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
print(A)

np.max(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


9

In [42]:
print(B)

np.max(B[0])

[[1 2 3]
 [4 5 6]]


3

In [43]:
print(C)

np.max(C[0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

## 3. Sum

In [44]:
# Untuk menjumlahkan seluruh elemen pada array dapat menggunakan "np.sum"
# Hanya akan menjumlahkan data dengan tipe numerik saja

A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
print(A)

np.sum(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


72

In [50]:
print(B)

np.sum(B[0])

[[1 2 3]
 [4 5 6]]


6

In [51]:
print(C)

np.sum(C[1,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


24

## 4. Mean (Rata - Rata)

In [30]:
# Rata-rata atau mean adalah salah satu ukuran pusat yang nilainya diperoleh dengan cara menjumlahkan semua nilai titik data yang ada lalu dibagi oleh jumlah data. 
# Untuk menghitung rata - rata sebuah data, maka dapat menggunakan "np.mean"

A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]


In [52]:
print(A)

np.mean(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


4.8

In [53]:
print(B)

np.mean(B[1])

[[1 2 3]
 [4 5 6]]


5.0

In [54]:
print(C)
np.mean(C[0,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


2.0

## 5. Median (Nilai Tengah)

In [55]:
# Median adalah salah satu ukuran pusat yang nilainya terletak di tengah titik data
# Untuk menghitung median sebuah data, maka dapat menggunakan "np.median"

A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
print(A)

np.median(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


5.0

In [57]:
print(B)

np.median(B[1])

[[1 2 3]
 [4 5 6]]


5.0

In [58]:
print(C)

np.median(C[1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


9.5

## 6. Modus

In [63]:
# Modus didefinisikan sebagai data yang memiliki frekuensi kemunculan terbanyak/terbesar.
# Ketika akan mencari sebuah "modus", maka harus import beberapa library lain,misalnya 'pandas', 'statistics' 
# Untuk menghitung modus sebuah data, maka dapat menggunakan "statistics.mode"

import statistics

In [84]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])


print(A)


[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


In [77]:
print(A)

statistics.mode(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


3

## 7. Kuantil

In [85]:
#Kuantil adalah nilai-nilai data yang membagi data yang telah diurutkan sebelumnya menjadi beberapa bagian yang sama besar ukurannya.
# Untuk menghitung kuantil sebuah data, maka dapat menggunakan "np.quantile"


A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [89]:
print(A)

np.quantile(A, .75)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


7.0

In [94]:
print(B)

np.quantile(B[0], .25)

[[1 2 3]
 [4 5 6]]


1.5

In [95]:
print(C)

np.quantile(C[1, 0], .50)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


8.0

## 8. Varians

In [106]:
# Variansi adalah ukuran sebaran pusat yang diperoleh dengan cara menghitung jarak antara tiap titik data pada sampel atau populasi dengan nilai mean.
# Untuk menghitung variab sebuah data, maka dapat menggunakan "np.var"


A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [98]:
print(A)

np.var(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


5.893333333333333

In [109]:
print(B)

np.var(B[1])

[[1 2 3]
 [4 5 6]]


0.6666666666666666

In [110]:
print(C)

np.var(C[1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


2.9166666666666665

## 9. Standar Deviation

In [116]:
# Standar Deviasi adalah ukuran sebaran pusat yang diperoleh dengan cara menarik akar kuadrat dari hasil perhitungan variansi.
# Untuk menghitung standar deviasi sebuah data, maka dapat menggunakan "np.std"


A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(A)
print(B)
print(C)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [114]:
print(A)

np.std(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


2.4276188608044165

In [113]:
print(B)

np.std(B[1])

[[1 2 3]
 [4 5 6]]


0.816496580927726

In [115]:
print(C)

np.std(C[1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


1.707825127659933