| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |


# NUMPY - Data Initialization

In [2]:
import numpy as np

## 1. Array From Values



In [8]:
# Untuk membuat sebuah array, cara yang pertama yaitu dengan membuat values yang akan dijadikan elemen dalam sebuah array
# Rumus : Variabel = np.array([value, value, value, dst...])

A = np.array([1,4,6,8,3,5,7,9,3])

print(A)

[1 4 6 8 3 5 7 9 3]


In [6]:
B = np.array([[1,2,3],[4,5,6]])

print(B)

[[1 2 3]
 [4 5 6]]


In [7]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 2. Array From Python List (or Tuple)



In [9]:
# Data List dapat dijadikan array, menggunakan cara sebagai berikut :
# Rumus : Variabel = np.array(list)

A = [1,4,6,8,3,5,7,9,3]
Array_A = np.asarray(A)

print(Array_A)

[1 4 6 8 3 5 7 9 3]


In [10]:
B = [1,2,3],[4,5,6]
Array_B = np.asarray(B)

print(Array_B)

[[1 2 3]
 [4 5 6]]


In [12]:
C = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
Array_C = np.asarray(C)
                      
print(Array_C)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 3. Empty Array

In [27]:
# Apabila tidak memiliki nilai yang akan dijadikan array, maka bisa menggunakan empty array
# Rumus : Variabel = np.empty(row, column)

D = np.empty((4,5))

print(Array_D)

[[6.23042070e-307 2.00272265e-307 2.89270636e-307 2.55899112e-307
  4.67289956e-307]
 [2.22522597e-306 1.33511969e-306 8.90070286e-308 1.69122046e-306
  1.24610723e-306]
 [1.02360867e-306 9.34611148e-307 1.24610383e-306 1.69118108e-306
  8.06632139e-308]
 [1.20160711e-306 1.69119330e-306 1.29062229e-306 1.24604136e-306
  1.39067116e-308]]


In [18]:
E = (3,5)
Array_E = np.empty(E)

print(Array_E)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 6.23047842e-307
  2.22522597e-306]
 [1.33511969e-306 1.37962320e-306 9.34604358e-307 9.79101082e-307
  1.78020576e-306]
 [1.69119873e-306 2.22522868e-306 1.24611809e-306 8.06632139e-308
  1.60221208e-306]]


## 4. Array of Ones

In [19]:
# Dengan "Ones" maka setiap value yang ada pada array akan bernilai "1"
# Rumus : Variabel = np.ones(column)

F = np.ones(6)

print(F)

[1. 1. 1. 1. 1. 1.]


In [21]:
G = np.ones((4,5))

print(G)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 5. Array of Zeros

In [22]:
# Dengan "Zeros" maka setiap value yang ada pada array akan bernilai "0"
# Rumus : Variabel = np.zeros(column)

H = np.zeros(5)

print(H)

[0. 0. 0. 0. 0.]


In [24]:
I = np.zeros((7,7))

print(I)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 6. Array of Any Value

In [25]:
# Value dalam array bisa ditentukan nilainya dengan cara sebagai berikut :
# Rumus : Variabel = np.full((row, column), value)

J = np.full((4,4), 15)

print(J)

[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [28]:
K = np.full((3,5), 50)

print(K)

[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]


## 7. Copy an Array

In [29]:
# Value dalam array dapat disalin dari array yang sudah ada
# Rumus : Variabel = np.copy(variabel array yang sudah ada)

L = np.copy(A)

print(L)

[1 4 6 8 3 5 7 9 3]


In [30]:
M = np.copy(C)

print(M)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 8. Sequential or Evenly Spaced Values

Ada beberapa cara untuk membuat array nilai berurutan atau berjarak sama dengan numpy.

### A. Numpy.Arange

In [31]:
# Value yang berurutan dalam array 1-D dapat ditentukan dengan menggunakan rumus sebagai berikut :
# Rumus : Variabel = np.arange(value)

N = np.arange(5)

print(N)

[0 1 2 3 4]


In [39]:
# Value pada array dapat ditentukan nilainya
# Rumus : Variabel = np.arange(value minimal, value maksimal)

P = np.arange(10,20)

print(P)

[10 11 12 13 14 15 16 17 18 19]


In [41]:
# Value pada array dapat ditentukan nilainya serta rentang nilai tersebut
# Rumus : Variabel = np.arange(value min, value maks, jarak)

Q = np.arange(10,30, 2)

print(Q)

[10 12 14 16 18 20 22 24 26 28]


In [37]:
# Value yang berurutan dalam array 2-D dapat ditentukan dengan menggunakan rumus sebagai berikut :
# Rumus : Variabel = np.arange(value).reshape((row, column))

O = np.arange(15).reshape((3,5))

print(O)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### B. Numpy.linspace

In [45]:
# Array dapat ditentukan jumlah valuenya menggunakan rumus berikut :
# Rumus : Variabel = np.linspace(value min, value maks, jumlah value)

R = np.linspace(1, 10, 5)
S = np.linspace(20, 40, 10)

print(R)
print(S)

[ 1.    3.25  5.5   7.75 10.  ]
[20.         22.22222222 24.44444444 26.66666667 28.88888889 31.11111111
 33.33333333 35.55555556 37.77777778 40.        ]


### C. Numpy.geomspace

In [49]:
# Numpy.geomspace menghasilkan nilai yang ditempatkan secara merata pada skala log
# Rumus : Variabel = np.geomspace(value min, value maks, jumlah value)

T = np.geomspace(1, 1000, 4)

print(T)

[   1.   10.  100. 1000.]


In [51]:
U = np.geomspace(1, 256, 9)

print(U)

[  1.   2.   4.   8.  16.  32.  64. 128. 256.]


## 9. Array of Random Values

In [61]:
# Value pada array dapat ditentukan dengan nilai (desimal) secara acak menggunakan rumus berikut :
# Rumus : Variabel = np.random.rand(row, column)

V = np.random.rand(3,3)

print(V)


[[0.50926248 0.58860882 0.30756459]
 [0.54635131 0.82287811 0.61526947]
 [0.04115593 0.21769838 0.95361493]]


In [65]:
# Value pada array dapat ditentukan dengan nilai (bilangan bulat) secara acak menggunakan rumus berikut :
# Rumus : Variabel = np.random.randint(value min, value maks, size = (row, column))

W = np.random.randint(1,40, size = (5,5))

print(W)

[[20 13 10 13  8]
 [24 33 31 20  5]
 [ 6  8 23 31 33]
 [35  2  9 20 22]
 [17 23 33 18 18]]


## 10. Array of Repeaded Values

In [66]:
# Value pada array dapat selalu dimunculkan sesuai dengan keinginan dengan rumus sebagai berikut :
# Rumus : Variabel = np.repeat(value, jumlah value)

X = np.repeat(10, 5)

print(X)

[10 10 10 10 10]


In [67]:
# Rumus : Variabel = np.repeat([value], jumlah value)

Y = np.repeat([3,4,5], 3)

print(Y)

[3 3 3 4 4 4 5 5 5]


In [69]:
# Rumus : Variabel = np.repeat([value, value, value], [jumlah value, jumlah value, jumlah value])

Z = np.repeat([2,3,4], [1,4,6])

print(Z)

[2 3 3 3 3 4 4 4 4 4 4]
