| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |

# NUMPY - Mathematics | Linear Algebra

In [1]:
import numpy as np

## 1. DOT

In [3]:
# "dot" merupakan fungsi perkalian pada matriks di aljabar linear

np.dot(10,5)

50

In [4]:
np.dot([1,2], [3,4])

11

In [7]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A)
print(B)
np.dot(A,B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [17]:
C = np.array([[7,8,9], [10,11,12]])
D = np.array([[1,2], [3,4], [5,6]])


print(C)
print(D)
np.dot(C,D)

[[ 7  8  9]
 [10 11 12]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 76, 100],
       [103, 136]])

In [19]:
E = np.array([[1,2], [3,4], [5,6]])
F = np.array([[7,8,9], [10,11,12]])


print(E)
print(F)
np.dot(E,F)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

## 2. INNER

In [23]:
np.inner(10,10)

100

In [27]:
np.inner([1,2], [3,4])

11

In [28]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A)
print(B)
np.inner(A,B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[17, 23],
       [39, 53]])

In [30]:
C = np.array([[7,8,9], [10,11,12]])
D = np.array([[1,2,3], [4,5,6]])


print(C)
print(D)
np.inner(C,D)

[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]


array([[ 50, 122],
       [ 68, 167]])

## 3. MATMUL

In [31]:
# "Matmul" memiliki fungsi yang sama dengan "dot"

np.dot(10,5)

50

In [32]:
np.dot([1,2], [3,4])

11

In [33]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A)
print(B)
np.matmul(A,B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [34]:
C = np.array([[7,8,9], [10,11,12]])
D = np.array([[1,2], [3,4], [5,6]])


print(C)
print(D)
np.matmul(C,D)

[[ 7  8  9]
 [10 11 12]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 76, 100],
       [103, 136]])

In [35]:
E = np.array([[1,2], [3,4], [5,6]])
F = np.array([[7,8,9], [10,11,12]])


print(E)
print(F)
np.dot(E,F)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

## 4. DETERMINANT

In [38]:
F = np.array([[1,2], [3,4]])

print(F)
np.linalg.det(F)

[[1 2]
 [3 4]]


-2.0000000000000004

In [52]:
G = np.random.randint(1,10, size = (3,3))


print(G)
np.linalg.det(G)

[[3 6 6]
 [4 1 4]
 [6 8 3]]


141.00000000000003

## 5. INVERSE

In [53]:
H = np.array([[2,-2], [2,2]])

print(H)

[[ 2 -2]
 [ 2  2]]


In [54]:
H_inv = np.linalg.inv(H)


print(H_inv)

[[ 0.25  0.25]
 [-0.25  0.25]]


In [55]:
# Untuk membuktikan apakah nilai invers benar, maka hasil inverse dikalikan dengan array murni sebelum di invers


np.dot(H,H_inv)

array([[1., 0.],
       [0., 1.]])