| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |

# NUMPY - Array Reorganization | Transpose, Concatenate, Split

In [1]:
import numpy as np

## 1. Transpose

Transpose array merupakan salah satu pembentukan kembali array.

### A. Transpose 1-D Array

In [4]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])

print(A)
np.transpose(A)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


array([3, 6, 7, 3, 6, 1, 5, 7, 2, 3, 7, 9, 2, 8, 3])

### B. Transpose 2-D Array

In [5]:
B = np.array([[1,2,3],[4,5,6]])

print(B)
np.transpose(B)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### C. Transpose 3-D Array

In [6]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C)
np.transpose(C)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

## 2. Concatenate

Concatenate merupakan fungsi pada NumPy untuk menggabungkan array

### A. Concatenate 1-D Array

In [10]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])
D = np.array([10,34,29,4])

print(A)
print(D)
np.concatenate((A,D))

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]
[10 34 29  4]


array([ 3,  6,  7,  3,  6,  1,  5,  7,  2,  3,  7,  9,  2,  8,  3, 10, 34,
       29,  4])

### B. Concatenate 2-D Array

In [13]:
B = np.array([[1,2,3],[4,5,6]])
E = np.array([[10,12,58],[98,74,24]])

print(B)
print(E)
np.concatenate((B,E), axis = 1)

[[1 2 3]
 [4 5 6]]
[[10 12 58]
 [98 74 24]]


array([[ 1,  2,  3, 10, 12, 58],
       [ 4,  5,  6, 98, 74, 24]])

In [14]:
B = np.array([[1,2,3],[4,5,6]])
E = np.array([[10,12,58],[98,74,24]])

print(B)
print(E)
np.concatenate((B,E), axis = 0)

[[1 2 3]
 [4 5 6]]
[[10 12 58]
 [98 74 24]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 12, 58],
       [98, 74, 24]])

In [29]:
np.concatenate((B,E), axis = None)

array([ 1,  2,  3,  4,  5,  6, 10, 12, 58, 98, 74, 24])

### C. Concatenate 3-D Array

In [17]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
F = np.array([[[98,39,24],[44,90,83]], [[43,23,66],[56,34,67]]])

print(C)
print(F)
np.concatenate((C,F), axis = 1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[98 39 24]
  [44 90 83]]

 [[43 23 66]
  [56 34 67]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [98, 39, 24],
        [44, 90, 83]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [43, 23, 66],
        [56, 34, 67]]])

In [18]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
F = np.array([[[98,39,24],[44,90,83]], [[43,23,66],[56,34,67]]])

print(C)
print(F)
np.concatenate((C,F), axis = 0)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[98 39 24]
  [44 90 83]]

 [[43 23 66]
  [56 34 67]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[98, 39, 24],
        [44, 90, 83]],

       [[43, 23, 66],
        [56, 34, 67]]])

In [21]:
np.concatenate(C)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.concatenate(F)

array([[98, 39, 24],
       [44, 90, 83],
       [43, 23, 66],
       [56, 34, 67]])

In [28]:
np.concatenate((C,F), axis = None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 98, 39, 24, 44, 90,
       83, 43, 23, 66, 56, 34, 67])

## 3. Split

Fungsi Split digunakan untuk melakukan proses pembagian elemen dari suatu array. Array akan dibagi menjadi N array (sesuai dengan jumlah yang telah ditentukan oleh pengguna) secara sama rata.

### A. Split 1-D Array

In [30]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])

print(A)
np.split(A,5)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


[array([3, 6, 7]),
 array([3, 6, 1]),
 array([5, 7, 2]),
 array([3, 7, 9]),
 array([2, 8, 3])]

### B. Split 2-D Array

In [31]:
B = np.array([[1,2,3],[4,5,6]])

print(B)
np.split(B, 2)

[[1 2 3]
 [4 5 6]]


[array([[1, 2, 3]]), array([[4, 5, 6]])]

### C. Split 3-D Array

In [47]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C)
np.array_split(C, 4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]]),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32)]