| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |

# NUMPY - Basic NumPy

### 1. IMPORT

In [1]:
# Hal pertama yang harus dilakukan ketika akan menggunakan library NumPy adalah dengan import NumPy tersebut.

import numpy as np

In [4]:
A = np.array([1,3,5,7,11])

print(A)

[ 1  3  5  7 11]


In [5]:
print(type(A))

<class 'numpy.ndarray'>


In [6]:
# Numpy bisa juga digunakan pada data Tuple

B = np.array((2,4,6,8))

print(B)

[2 4 6 8]


### 2. Beberapa cara untuk membuat data List/Array

#### A. Sederhana

In [25]:
angka = np.array([1,3,5,3,6,8,3,5,9])

print(angka)

[1 3 5 3 6 8 3 5 9]


#### B. Range

In [28]:
Range = np.arange(1,15,2)

print(Range)


# (batas bawah, batas atas, jarak antar angka)

[ 1  3  5  7  9 11 13]


#### C. Linear Space/Linspace

In [31]:
# Melalui Linspace, array dapat ditentukan akan menjadi berapa bagian


LP = np.linspace(1,15,5)

print(LP)

# (batas bawah, batas atas, berapa bagian)

[ 1.   4.5  8.  11.5 15. ]


### 3. DIMENSI PADA ARRAY

#### A. 0 DIMENSI ARRAY

Setiap Value pada Array adalah Array 0-Dimensi 

In [7]:
C = np.array(15)

print(C)

15


#### B. 1 DIMENSI ARRAY

Array yang memiliki 0-Dimensi pada setiap valuenya sebagai elemen maka disebut Array 1-Dimensi. Array 1-D ini adalah array yang paling standar digunakan

In [8]:
D = np.array([1,2,3,4,5])

print(D)

[1 2 3 4 5]


#### C. 2 DIMENSI ARRAY

Array yang memiliki 1-Dimensi pada setiap valuenya sebagai elemen maka disebut Array 2-Dimensi. Biasanya disebut sebagai sebuah matriks.

In [9]:
E = np.array([[1,2,3],[4,5,6]])

print(E)

[[1 2 3]
 [4 5 6]]


#### D. 3 DIMENSI ARRAY

Array yang memiliki 2-Dimensi pada setiap valuenya (matriks) sebagai elemen maka disebut Array 3-Dimensi.

In [12]:
F = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(F)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
# Cara untuk cek array tersebut termasuk array berapa dimensi dapat menggunakan ".ndim"

C = np.array(15)
D = np.array([1,2,3,4,5])
E = np.array([[1,2,3],[4,5,6]])
F = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C.ndim)
print(D.ndim)
print(E.ndim)
print(F.ndim)

0
1
2
3


### 4. INDEXING

#### A. INDEXING 1 DIMENSI ARRAY

In [17]:
D = np.array([1,2,3,4,5])

print(D[0])
print(D[3])
print(D[0] + D[3])

1
4
5


#### B. INDEXING 2 DIMENSI ARRAY

In [20]:
E = np.array([[1,2,3],[4,5,6]])

print(E[0,1])
print(E[1,2])

# [row,column]

2
6


#### C. INDEXING 3 DIMENSI ARRAY

In [22]:
F = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(F[0,1,1])
print(F[1,0,0])

# [array-,row,column]

5
7


#### D. NEGATIVE INDEXING

In [24]:
# Negative Indexing untuk mengakses elemen yang paling akhir setiap array

E = np.array([[1,2,3],[4,5,6]])

print(E[0,-1])
print(E[1,-1])

3
6
