| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |



# NUMPY - Array Reorganization | Reshape, Vertical Stack, Horizontal Stack

In [1]:
import numpy as np

## 1. Reshape

Reshape merupakan salah satu teknik untuk mengubah bentuk matriks. Pada fungsi "reshape" hanya ukurannya yang dibalik, bukan matriksnya. Reshape bisa dilakukan untuk semua bentuk matriks, selama dimensi array memenuhi.

### A. Reshape 1-D Array to  2-D Array

In [12]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3])

print(A)
A.reshape(5,3)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3]


array([[3, 6, 7],
       [3, 6, 1],
       [5, 7, 2],
       [3, 7, 9],
       [2, 8, 3]])

In [13]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3,8])

print(A)
A.reshape(4,4)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3 8]


array([[3, 6, 7, 3],
       [6, 1, 5, 7],
       [2, 3, 7, 9],
       [2, 8, 3, 8]])

### B. Reshape 1-D Array to 3-D Array

In [17]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3,8])

print(A)
A.reshape(2,4,2)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3 8]


array([[[3, 6],
        [7, 3],
        [6, 1],
        [5, 7]],

       [[2, 3],
        [7, 9],
        [2, 8],
        [3, 8]]])

In [20]:
A = np.array([3,6,7,3,6,1,5,7,2,3,7,9,2,8,3,8])

print(A)
A.reshape(4,2,2)

[3 6 7 3 6 1 5 7 2 3 7 9 2 8 3 8]


array([[[3, 6],
        [7, 3]],

       [[6, 1],
        [5, 7]],

       [[2, 3],
        [7, 9]],

       [[2, 8],
        [3, 8]]])

### C. Reshape 2-D Array to 1-D Array

In [22]:
B = np.array([[1,2,3],[4,5,6]])

print(B)
B.reshape(-1)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

### D. Reshape 2-D Array to 3-D Array

In [23]:
B = np.array([[1,2,3],[4,5,6]])

print(B)
B.reshape(3,1,2)

[[1 2 3]
 [4 5 6]]


array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

### E. Reshape 3-D Array to 1-D Array

In [25]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C)
C.reshape(-1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### F. Reshape 3-D Array to 2-D Array

In [26]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(C)
C.reshape(4,3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 2. Vertical Stack

Vertikal Stack digunakan untuk menggabungkan array secara vertikal.

### A. Vertical Stack 1-D Array

In [31]:
D = np.array([2,4,6,3,2,7,4,8,4])
E = np.array([7,3,8,6,4,8,5,3,7])

print(D)
print(E)

np.vstack((D,E))

[2 4 6 3 2 7 4 8 4]
[7 3 8 6 4 8 5 3 7]


array([[2, 4, 6, 3, 2, 7, 4, 8, 4],
       [7, 3, 8, 6, 4, 8, 5, 3, 7]])

### B. Vertical Stack 2-D Array

In [38]:
B = np.array([[1,2,3],[4,5,6]])
F = np.array([[20,48,19],[90,83,92]])

print(B)
print(F)

np.vstack((B,F))

[[1 2 3]
 [4 5 6]]
[[20 48 19]
 [90 83 92]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20, 48, 19],
       [90, 83, 92]])

### C. Vertical Stack 3-D Array

In [41]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
G = np.array([[[83,75,28], [46,98,22]],[[24,48,29],[33,70,45]]])

print(C)
print(G)

np.vstack((C,G))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[83 75 28]
  [46 98 22]]

 [[24 48 29]
  [33 70 45]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[83, 75, 28],
        [46, 98, 22]],

       [[24, 48, 29],
        [33, 70, 45]]])

## 3. Horizontal Stack

Vertikal Stack digunakan untuk menggabungkan array secara horizontal.

### A. Horizontal Stack 1-D Array

In [32]:
D = np.array([2,4,6,3,2,7,4,8,4])
E = np.array([7,3,8,6,4,8,5,3,7])

print(D)
print(E)

np.hstack((D,E))

[2 4 6 3 2 7 4 8 4]
[7 3 8 6 4 8 5 3 7]


array([2, 4, 6, 3, 2, 7, 4, 8, 4, 7, 3, 8, 6, 4, 8, 5, 3, 7])

In [39]:
B = np.array([[1,2,3],[4,5,6]])
F = np.array([[20,48,19],[90,83,92]])

print(B)
print(F)

np.hstack((B,F))

[[1 2 3]
 [4 5 6]]
[[20 48 19]
 [90 83 92]]


array([[ 1,  2,  3, 20, 48, 19],
       [ 4,  5,  6, 90, 83, 92]])

In [42]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
G = np.array([[[83,75,28], [46,98,22]],[[24,48,29],[33,70,45]]])

print(C)
print(G)

np.hstack((C,G))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[83 75 28]
  [46 98 22]]

 [[24 48 29]
  [33 70 45]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [83, 75, 28],
        [46, 98, 22]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [24, 48, 29],
        [33, 70, 45]]])