| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" style="height:150px"> |
| --- | --- |


# NUMPY - Mathematics | Basic Arithmetic

In [1]:
import numpy as np

## 1. Arithmetic Operations

In [21]:
A = np.array([1,4,6,8,3,5,7,9,3])

A + 5

array([ 6,  9, 11, 13,  8, 10, 12, 14,  8])

In [22]:
A = np.array([1,4,6,8,3,5,7,9,3])

A - 2

array([-1,  2,  4,  6,  1,  3,  5,  7,  1])

In [23]:
A = np.array([1,4,6,8,3,5,7,9,3])

A * 10

array([10, 40, 60, 80, 30, 50, 70, 90, 30])

### A. add

In [9]:
# Untuk menambahkan setiap elemen dapat menggunakan "np.add" sebagai pengganti "+"

np.add(2,5)

7

In [5]:
np.add(10,20)

30

In [17]:
A = np.array([5,3,6])
B = np.arange(11,20).reshape(3,3)

print(B)
np.add(A,B)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[16, 15, 19],
       [19, 18, 22],
       [22, 21, 25]])

In [20]:
C = np.arange(1,10).reshape(3,3)
D = np.arange(21,30).reshape(3,3)


print(C)
print(D)
np.add(C,D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

### B. multiply

In [27]:
# Untuk mengalikan setiap elemen dapat menggunakan "np.multiply" sebagai pengganti "*" 

A = np.array([1,4,6,8,3,5,7,9,3])

print(A)
A * 10

[1 4 6 8 3 5 7 9 3]


array([10, 40, 60, 80, 30, 50, 70, 90, 30])

In [26]:
A = np.array([5,3,6])
B = np.arange(11,20).reshape(3,3)

print(A)
print(B)
np.multiply(A,B)

[5 3 6]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[ 55,  36,  78],
       [ 70,  45,  96],
       [ 85,  54, 114]])

In [28]:
C = np.arange(1,10).reshape(3,3)
D = np.arange(21,30).reshape(3,3)

print(C)
print(D)
np.multiply(C,D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

### C. divide

In [30]:
# Untuk membagi setiap elemen dapat menggunakan "np.divide" sebagai pengganti "/"

A = np.array([1,4,6,8,3,5,7,9,3])

print(A)
A / 10

[1 4 6 8 3 5 7 9 3]


array([0.1, 0.4, 0.6, 0.8, 0.3, 0.5, 0.7, 0.9, 0.3])

In [31]:
A = np.array([5,3,6])
B = np.arange(11,20).reshape(3,3)

print(A)
print(B)
np.divide(A,B)

[5 3 6]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[0.45454545, 0.25      , 0.46153846],
       [0.35714286, 0.2       , 0.375     ],
       [0.29411765, 0.16666667, 0.31578947]])

In [32]:
C = np.arange(1,10).reshape(3,3)
D = np.arange(21,30).reshape(3,3)

print(C)
print(D)
np.divide(C,D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


array([[0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923],
       [0.25925926, 0.28571429, 0.31034483]])

### D. Power

In [33]:
# Untuk melakukan perpangkatan setiap elemen dapat menggunakan "np.power" sebagai pengganti "**"

A = np.array([1,4,6,8,3,5,7,9,3])

print(A)
np.power(A,2)

[1 4 6 8 3 5 7 9 3]


array([ 1, 16, 36, 64,  9, 25, 49, 81,  9], dtype=int32)

In [36]:
A = np.array([1,4,6,8,3,5,7,9,3])
E = np.array([6,7,3,2,8,5,8,5,6])

print(A)
print(E)
np.power(A,E)

[1 4 6 8 3 5 7 9 3]
[6 7 3 2 8 5 8 5 6]


array([      1,   16384,     216,      64,    6561,    3125, 5764801,
         59049,     729])

In [39]:
F = np.array([2,2,2,2,2])
G = np.array([[5,8,5,8,2], [7,3,6,8,4]])

print(F)
print(G)
np.power(F,G)

[2 2 2 2 2]
[[5 8 5 8 2]
 [7 3 6 8 4]]


array([[ 32, 256,  32, 256,   4],
       [128,   8,  64, 256,  16]])

In [41]:
G = np.array([[5,8,5,8,2], [7,3,6,8,4]])
H = np.array([[1,2,3,1,3], [2,3,1,4,2]])

print(G)
print(H)

np.power(G,H)

[[5 8 5 8 2]
 [7 3 6 8 4]]
[[1 2 3 1 3]
 [2 3 1 4 2]]


array([[   5,   64,  125,    8,    8],
       [  49,   27,    6, 4096,   16]])

## 2. Trigonometric Functions

### A. Sin(x) Function

In [45]:
J = np.arange(10)

print(J)
np.sin(J)

[0 1 2 3 4 5 6 7 8 9]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### B. Cos(x) Function

In [46]:
J = np.arange(10)

print(J)
np.cos(J)

[0 1 2 3 4 5 6 7 8 9]


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

### C. Tan(x) Function

In [47]:
J = np.arange(10)

print(J)
np.tan(J)

[0 1 2 3 4 5 6 7 8 9]


array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

## 3. Eksponents and Logarithm

### A. Eksponential Function

In [52]:
np.exp(5)

148.4131591025766

In [53]:
A = np.array([1,4,6,8,3,5,7,9,3])

np.exp(A)

array([2.71828183e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.00855369e+01, 1.48413159e+02, 1.09663316e+03, 8.10308393e+03,
       2.00855369e+01])

In [54]:
import matplotlib.pyplot as plt

In [56]:
K = np.linspace(1,10, 100)

L = np.exp(K)

plt.plot(K, L)
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

### B. Logarithm Function

In [60]:
np.log(10)

2.302585092994046

In [61]:
A = np.array([1,4,6,8,3,5,7,9,3])

print(A)
np.log(A)

[1 4 6 8 3 5 7 9 3]


array([0.        , 1.38629436, 1.79175947, 2.07944154, 1.09861229,
       1.60943791, 1.94591015, 2.19722458, 1.09861229])